### ISSUE TITLE
record cards are missing

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#49] opened 2020-02-10 15:04 UTC
Upps, New issue, 
Users cannot access to detail cards of their own records. Therefore they also cannot edit anything, names, location, upload images...

**Comment by DavidRoy** [comment] 2020-02-10 20:34
There is a record edit icon (pencil/pad image) on the right hand-side of the explore my-records data grid.  

I have just tested this by masquerading as account, user = 'enetwild' and editing a record.  See:
https://european-mammals.brc.ac.uk/record/details?occurrence_id=12552130
where the submission_date = 'Entered on 8th January 2020 at 07:50 and last updated on 10th February 2020 at 20:29'

**Comment by JotablancoA** [comment] 2020-02-11 12:41
Thanks, but, when i click in your link i got this message. "page not found"
(see image capture below)
When i try to edit any records using record edit icon (pencil/pad image)We
got the same error messages.
we  tested with other 3 different users (different computers),  obtaining
the same issue.




[image: imagen.png]

**Comment by DavidRoy** [comment] 2020-02-11 16:23
@JotablancoA the image is missing from the post.  
But I think I now understand that this issue is with the edit option from within the verification system?

@johnvanbreda can you resolve this issue.  When masquerading as Jota's account (https://european-mammals.brc.ac.uk/en/user/11), within the verification page, selecting a record and clicking on the edit icon the page returns a 'page not found' and links to: https://european-mammals.brc.ac.uk/edit-generic-record?occurrence_id=12793501

verifiers require record editing rights

I notice that the record-edit page for a user's own records has a different url.
https://european-mammals.brc.ac.uk/record/edit?occurrence_id=12793501

**Comment by JotablancoA** [comment] 2020-02-11 16:50
I think you are just now working on this issue,

I'm going to try to give more details about the problem:

This occurs not only for editing the records:

We dont get to access to the page to view records details from my records
in “Explore my records”  or in “Explore all records”  tabs

https://european-mammals.brc.ac.uk/record/details?occurrence_id=12610015

https://european-mammals.brc.ac.uk/record/details?occurrence_id=12790258

I don’t get editing the records in “Explore my records” tab or
“Verification as reported David

Best,


In all cases we receive an error message “no page found”

**Comment by DavidRoy** [comment] 2020-02-11 17:17
@JotablancoA I can't replicate the problem of viewing records from the explore pages.  Can you confirm the account you are logged in as.  Also what web browser you are using.
thanks

**Comment by JotablancoA** [comment] 2020-02-12 10:02
Dear David,

I tested it using different devices and three different users  getting the
same error message

   - Windows (Firefox and Chrome)
   - Mac (Safari and Chrome)
   - Linux (Firefox)

My user is  jota blanco  (jota.blanco@gmail.com).  I also tried to change
language configuration (in my profile) to English languages but was not
successful, I got  again the same error.

**Comment by johnvanbreda** [comment] 2020-02-12 10:03
I've fixed the edit button on the verification page but, like David, can't reproduce the problems with record details links from the Explore pages (Mac Chrome). I'll do some more testing on another laptop where I can change the OS language to Spanish.

**Comment by johnvanbreda** [comment] 2020-02-12 10:32
Thanks @JotablancoA - I've reproduced this now. The Indicia link code is not clever enough to work out the translated link as it stands (/es/record/detalles). I'm just checking with the developer of another project as to the best way forward for setting this up properly as there are a couple of options.

**Comment by JotablancoA** [comment] 2020-02-12 13:02
This problem was arise recently, Some week ago i got to see records details
correctly
Could it be associated with changes for authomatic language in the web
Should I  change any code tin transsifex?

**Comment by DavidRoy** [comment] 2020-02-20 10:06
@johnvanbreda this is the most urgent issue with iMammalia currently as it affects users and verifiers in editing the records

**Comment by johnvanbreda** [comment] 2020-02-20 17:27
This should now be sorted. I added new code to preserve the language paths in URLs from the links on this page.
Whilst trying to fix this I removed the Spanish translated page for record details as I'd thought that to be the problem. However I found that removing this was only a partial fix and the correct fix meant this was unnecessary. However I suspect it is better to just have a single language independent version of each Indicia page and translate the individual strings, rather than translating the whole page.

**Comment by JotablancoA** [comment] 2020-02-20 18:41
Thanks, you solved one of the issues, but not all. Let me explain

1 ) As a user, now i can see record details cards, but i dont get to edit
my own records.
Receiving this error message
Page not found ; The requested page could not be found.
2) I  also can see record details in "explore all records tab"
3) As verifier i can not edit any record (same error message), however as i
discover this functionality recently i am not sure if was working correctly
before the issue of  language crash

Best,

**Comment by johnvanbreda** [comment] 2020-02-25 10:00
1) and 3) fixed by correcting the path to the record edit page. 
2) is as designed.

**Closed as completed by johnvanbreda** 2020-02-25 10:00 UTC
